services:
  - type: web
    name: ss-wakeel-bot
    env: node
    branch: master
    repo: https://github.com/pbitdtlogin-gif/ss-wakeel-bot
    buildCommand: npm install
    startCommand: node bot.js
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: GITHUB_TOKEN
        sync: false
      - key: OWNER_ID
        value: "8277131084"
    autoDeploy: true
    healthCheckPath: /
    plan: free